# Generated by Django 3.2 on 2021-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
