# Generated by Django 3.2 on 2021-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('NEW', 'Newbie'), ('PRO', 'Pro')], default='NEW', max_length=3),
        ),
    ]
