# Generated by Django 3.2 on 2021-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pwd_hash',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_pwd_time',
            field=models.DateTimeField(null=True),
        ),
    ]
